export default {
  games: [
    { name: 'MĒRĶIS',
      image: 'games/merkis.jpg',
      about: ['Reālā laika biznesa simulācija',
        'Mērķu uzstādīšana un sasniegšana',
        'Taktiskā vadība',
        'Resursu plānošana',
        'Komunikācija un sadarbība',
        'Peļņu ietekmējošie faktori',
        'Struktūtvienību mijiedarbība rezultātu sasniegšanā'] },
    { name: 'TIME MENTOR OFFICE',
      image: 'games/tmo.jpg',
      about: ['Personiskās efektivitātes paaugstināšana',
        'Prioritāšu noteikšana',
        'Laika plānošana',
        'Lēmumu pieņemšana komandā'] },
    { name: 'SITUĀCIJAS PIRĀTS',
      image: 'games/situacijaspirats.jpg',
      about: [ 'Situatīvā līderība',
        'Lēmumu pieņemšana',
        'Uzdevumu nodošana',
        'Darbinieku gatavības izvērtēšana' ] },
    { name: 'HOW COULD IT BE?',
      image: 'games/howcoulditbe.jpg',
      about: ['Nolūku atpazīšana',
        'Emocionālā inteliģence',
        'Neefektīvie un efektīvie nolūki',
        'Konstruktīva atgriezeniskā saite'] },
    { name: 'SALAS UN TILTI',
      image: 'games/salasuntilti.jpg',
      about: ['Efektīvas komunikācijas pamatprincipi',
        'Ilgtspējīgu attiecību izveidošana',
        'Atgriezeniskās saites nozīme',
        'Kongruence komandā'] },
    { name: 'VADĪBAS MAESTRO',
      image: 'games/maestro.jpg',
      about: ['Darbinieku motivēšana',
        'Deleģēšanas pamatprincipi',
        'Kritika un uzslavas',
        'Uz mērķi vērsta uzdevumu došana un kontrole'] },
    { name: 'LIDOSTA',
      image: 'games/lidosta.jpg',
      about: ['Lēmumu pieņemšana mainīgā vidē',
        'Vienošanās par kopīgiem noteikumiem komandā',
        'Operatīvas vadības iemaņas',
        'Sadarbība starp konkurējošām struktūrvienībām'] },
    { name: 'DZĪVĀS VĒRTĪBAS',
      image: 'games/dzivasvertibas.jpg',
      about: ['Personiskās un uzņēmuma vērtības',
        'Korporatīvo vērtību iedzīvināšana',
        'Vērtību pārnese ikdienas darbībās',
        'Vērtību nozīme problēmu risināšanā'] },
    { name: 'FRONTLINE',
      image: 'games/frontline.jpg',
      about: ['Izcilas klientu apkalpošanas principi',
        'Darbs ar sarežģītiem klientiem',
        'Uzvedības iemaņu treniņš',
        'Klientu apkalpošanas pieredzes apmaiņa'] },
    { name: 'PĀRRUNU PAVĒLNIEKS',
      image: 'games/parrunupavelnieks.jpg',
      about: [ 'Pārrunu mērķa noteikšana un sasniegšana',
        'Pārrunu taktikas',
        'Savu interešu aizstāvēšana',
        'Manipulāciju atpazīšana',
        'Pārliecināšana un argumentēšana'] },
    { name: 'UPSALES',
      image: 'games/upsales.jpg',
      about: ['Pārdošanas pamatalgoritms',
        'Papildpārdošana',
        'Vajadzību izzināšana',
        'Iebildumu atspēkošana'] },
    { name: 'SAPROTI MANI, JA VARI',
      image: 'games/saprotimanijavari.jpg',
      about: ['Klienta vajadzību noskaidrošanas algoritms',
        'Mērķtiecīgu jautājumu uzdošana',
        'Klienta kritēriju izmantošana argumentācijā',
        'Prasme runāt klientu valodā'] },
    { name: 'JĀ/NĒ/VARBŪT',
      image: 'games/yesnomaybe.jpg',
      about: ['5 argumentēšanas metodes',
        'Pareizo argumentu izvēle',
        'Pārliecinoša un uz rezultātu vērsta komunikācija',
        'Iebildumu analīze'] },
    { name: 'UNLIMITED ME',
      image: 'games/unlimitedme.jpg',
      about: ['4 koučinga metodes',
        'Koučinga izmantošana vadīšanā',
        'Mērķa uzstādīšana',
        'Mērķa sasniegšanas plāna izvirzīšana'] },
    { name: 'ZELTA RESURSS',
      image: 'games/zeltaresurss.jpg',
      about: ['Sasniedzamajam mērķim atbilstošanas komandas izveidošana',
        'Izpratne par personālu kā vērtību un resursu',
        'FinaNsiālā ieguldījuma efektivitāte personālvadībā',
        'Komandas attīstības dinamika'] }
  ],
  seminars: [
    { name: 'VADĪTPRASME',
      image: 'seminars/vaditprasme.jpg',
      about: ['Vadītāja un līdera galvenās atbildības un pienākumi',
        'Darbinieku motivēšanas instrumenti un iemaņas',
        'Deleģēšana un uzdevumu došana',
        'Darbinieku potenciāla novērtēšana un attīstīšana',
        'Efektīvas komunikācijas un pārliecināšanas tehnikas']
    },
    { name: 'PĀRDOTPRASME',
      image: 'seminars/pardotprasme.jpg',
      about: ['Klienta vajadzību izzināšanas instrumenti',
        'Rezultatīvu attiecību veidošanas pamatprincipi',
        'Pašmotivācija un mērķu sasniegšana',
        'Pretestības un iebildumu pārvarēšana',
        'Darījumu noslēgšana un ilgtermiņa attiecību uzturēšana']
    },
    { name: 'LIETIŠĶĀS PĀRRUNAS',
      image: 'seminars/parrunu_vad_noslepumi.jpg',
      about: ['Varas un attiecību līdzsvars',
        'Pārrunu mērķi un taktikas',
        'Neverbālās komunikācijas atpazīšana un izmantošana',
        'Ietekmējošas komunikācijas paņēmieni']
    },
    { name: 'PRIORITĀTES UN LAIKA PLĀNOŠANA',
      image: 'seminars/prioritates.jpg',
      about: ['Īstermiņa un ilgtermiņa mērķi',
        'Prioritāšu noteikšana',
        'Rezultatīvas plānošanas pamati',
        'Prduktīva vai nelietderīga laika izmantošana']
    },
    { name: 'KONFLIKTU RISINĀŠANA',
      image: 'seminars/konfliktu_ris.jpg',
      about: ['Konfliktu risināšanas fāzes',
        'Konfliktu risināšanas stratēģijas',
        'Emociju vadīšana konfliktā',
        'Konfliktā iesaistīto pušu mērķi un nolūki']
    },
    { name: 'INOVATĪVĀ DOMĀŠANA BIZNESĀ',
      image: 'seminars/inovativa_domasana.jpg',
      about: ['Inovatīvas domāšanas metodes',
        'Ideju radīšanu veicinošie uzskati',
        'Inovācijām draudzīgas kultūras uzturēšana',
        'Idejas pārvēršana darbību plānā']
    },
    { name: 'PĀRLIECINOŠAS UZSTĀŠANĀS PRASMES',
      image: 'seminars/prezentesanas_prasmes.jpg',
      about: ['Uzstāšanās mērķi',
        'Auditorijas vadīšanas paņēmieni',
        'Efektīva informācijas nodošana',
        'Verbālā un neverbālā komunikācija']
    },
    { name: 'FINANSES VADĪTĀJIEM',
      image: 'seminars/finanses_vaditajiem.jpg',
      about: ['Vadības grāmatvedības stratēģijas',
        'Finanšu plānošana un analīze',
        'Budžets, naudas plūsma, peļņas un zaudējumu aprēķins',
        'Finanšu rādītāju savstarpējā korelācija']
    },
    { name: 'KOMANDAS SALIEDĒŠANA',
      image: 'seminars/komandas_trenins.jpg',
      about: ['Efektīvas komandas kritēriji un modelis',
        'Lomas un noteikumi komandā',
        'Virzība uz kopīgu mērķi',
        'Uz rezultātu vērsta savstarpējā komunikācija']
    },
    { name: 'KRITISKĀ DOMĀŠANA',
      image: 'seminars/kritiskadomasana.jpg',
      about: ['Cilvēku domāšanas tipi',
        'Informācijas filtri',
        'Faktu iegūšana pretstatā interpretācijai',
        'Objektīvas interpretācijas parametri']
    },
    { name: 'PĀRMAIŅU DOMĀŠANAS STRATĒĢIJA',
      image: 'seminars/parmainu_domasanas_strategija.jpg',
      about: ['Problēmas definēšana',
        'Problēmu risināšanas idejas',
        'Uz risinājumu vērstas darba kultūras radīšana',
        'Pretošanās iemesli pārmaiņām']
    },
    { name: 'TRENERU TRENIŅŠ',
      image: 'seminars/koucings.jpg',
      about: ['Treniņa mērķi',
        'Apmācību formas un satura veidošanas principi',
        'Iesaisti stimulējoša vide',
        'Darbs ar sarežģītiem klausītājiem',
        'Praktiskā darbība un vingrinājumi']
    }
  ],
  persons: [
    { name: 'VALDIS PURIŅŠ',
      image: 'people/valdisnop.jpg' },
    { name: 'IEVA SAULĪTE',
      image: 'people/ievanop.jpg' },
    { name: 'ARTŪRS GERGELĒVIČS',
      image: 'people/artursnop.jpg' },
    { name: 'SERGEJS MASLOBOJEVS',
      image: 'people/sergejsnop.jpg' },
    { name: 'EIRA SARNOVSKA',
      image: 'people/eira.jpg' },
    { name: 'ALEKSIS DAUME',
      image: 'people/aleksisnop.jpg' },
    { name: 'KRISTIĀNA GRĀVĪTE',
      image: 'people/kristiananop.jpg' },
    { name: 'EMĪLS BRIGMANIS',
      image: 'people/emilsnop.jpg' },
    { name: 'ADRIANS OSKIRKO',
      image: 'people/adriansnop.jpg' },
    { name: 'UĢIS STRAUSS',
      image: 'people/ugisnop.jpg' }
  ],
  stories: [
    { name: 'kāpjam kalnos',
      image: 'banner2.jpg' },
    { name: 'spēlējam florbolu',
      image: 'stories/florbols.jpeg' },
    { name: 'organizējam nometnes bērniem',
      image: 'stories/upe.jpg' },
    { name: 'spēlējam hokeju',
      image: 'stories/hokejs.jpeg' },
    { name: 'braucam misijās',
      image: 'stories/misijas.jpeg' },
    { name: 'ejam pārgājienos',
      image: 'stories/pargajieni.jpg' },
    { name: 'sienam sieru',
      image: 'stories/siers.jpg' },
    { name: 'braucam ar laivām',
      image: 'stories/laivas.jpg' },
    { name: 'muzicējam',
      image: 'stories/muzika.jpeg' },
    { name: 'organizējam mūzikas festivālus',
      image: 'stories/festivals.jpg' },
    { name: 'spēlejam šahu',
      image: 'stories/sahs.jpg' }
  ],
  partners: [
    { name: 'Starptautiski',
      image: 'logo/nti-int.png',
      email: 'office@nti-group.com',
      number: '+37129288892',
      link: 'www.nti-group.com' },
    { name: 'Krievija',
      image: 'logo/nti-su.png',
      email: 'nti@nti.su',
      number: '+7(495)6400662, +7(812)6400662',
      link: 'www.nti.su' },
    { name: 'Ukraina',
      image: 'logo/nti-ua.jpg',
      email: 'info@nordic.in.ua',
      number: '+380442286816, +380948286818',
      link: 'www.nordic.in.ua' }
  ],
  contacts: [
    { name: 'CooolToool',
      image: 'logo/coooltoool.png',
      email: 'office@coooltoool.net',
      link: 'http://coooltoool.net' },
    { name: 'IM Games',
      image: 'logo/imgames.png',
      email: 'office@im-games.org',
      link: 'http://im-games.org' },
    { name: 'Viennese',
      image: 'logo/viennese.png',
      email: 'office@viennese.org',
      link: 'http://viennese.org/' }
  ]
}
