export default {
  games: [
    { name: 'MĒRĶIS',
      image: 'games/merkis.jpg',
      about: ['ReEĀLĀ LAIKA BIZNESA SIMULĀCIJA',
        'MĒRĶU UZSTĀDĪŠANA UN SASNIEGŠANA',
        'TAKTISKĀ VADĪBA',
        'RESURSU PLĀNOŠANA',
        'KOMUNIKĀCIJA UN SADARBĪBA',
        'PEĻŅU IETEKMĒJOŠIE FAKTORI',
        'STRUKTŪTVIENĪBU MIJIEDARBĪBA REZULTĀTU SASNIEGŠANĀ'] },
    { name: 'TIME MENTOR OFFICE',
      image: 'games/timementoroffice.jpg',
      about: ['PERSONISKĀS EFEKTIVITĀTES PAAUGSTINĀŠANA',
        'PRIORITĀŠU NOTEIKŠANA',
        'LAIKA PLĀNOŠANA',
        'LĒMUMU PIEŅEMŠANA KOMANDĀ'] },
    { name: 'SITUĀCIJAS PIRĀTS',
      image: 'games/situacijaspirats.jpg',
      about: [ 'SITUATĪVĀ LĪDERĪBA',
        'LĒMUMU PIEŅEMŠANA',
        'UZDEVUMU NODOŠANA',
        'DARBINIEKU GATAVĪBAS IZVĒRTĒŠANA' ] },
    { name: 'HOW COULD IT BE?',
      image: 'games/howcoulditbe.jpg',
      about: ['NOLŪKU ATPAZĪŠANA',
        'EMOCIONĀLĀ INTELIĢENCE',
        'NEEFEKTĪVIE UN EFEKTĪVIE NOLŪKI',
        'KONSTRUKTĪVA ATGRIEZENISKĀ SAITE'] },
    { name: 'SALAS UN TILTI',
      image: 'games/salasuntilti.jpg',
      about: ['EFEKTĪVAS KOMUNIKĀCIJAS PAMATPRINCIPI',
        'ILGTSPĒJĪGU ATTIECĪBU IZVEIDOŠANA',
        'ATGRIEZENISKĀS SAITES NOZĪME',
        'KONGRUENCE KOMANDĀ'] },
    { name: 'VADĪBAS MAESTRO',
      image: 'games/komandashokejs.jpg',
      about: ['DARBINIEKU MOTIVĒŠANA',
        'DELEĢĒŠANAS PAMATPRINCIPI',
        'KRISTIKA UN UZSLAVAS',
        'UZ MĒRĶI VĒRSTA UZDEVUMU DOŠANA UN KONTROLE'] },
    { name: 'LIDOSTA',
      image: 'games/lidosta.jpg',
      about: ['LĒMUMU PIEŅEMŠANA MAINĪGĀ VIDĒ',
        'VIENOŠANĀS PAR KOPĪGIEM NOTEIKUMIEM KOMANDĀ',
        'OPERATĪVAS VADĪBAS IEMAŅAS',
        'SADARBĪBA STARP KONKURĒJOŠĀM STRUKTŪRVIENĪBĀM'] },
    { name: 'DZĪVĀS VĒRTĪBAS',
      image: 'games/dzivasvertibas.jpg',
      about: ['PERSONISKĀS UN UZŅĒMUMA VĒRTĪBAS',
        'KORPORATĪVO VĒRTĪBU IEDZĪVINĀŠANA',
        'VĒRTĪBU PĀRNESE IKDIENAS DARBĪBĀS',
        'VĒRTĪBU NOZĪME PROBLĒMU RISINĀŠANĀ'] },
    { name: 'FRONTLINE',
      image: 'games/frontline.jpg',
      about: ['IZCILAS KLIENTU APKALPOŠANAS PRINCIPI',
        'DARBS AR SAREŽĢĪTIEM KLIENTIEM',
        'UZVEDĪBAS IEMAŅU TRENIŅŠ',
        'KLIENTU APKALPOŠANAS PIEREDZES APMAIŅA'] },
    { name: 'PĀRRUNU PAVĒLNIEKS',
      image: 'games/parrunupavelnieks.jpg',
      about: [ 'PĀRRUNU MĒRĶA NOTEIKŠANA UN SASNIEGŠANA',
        'PĀRRUNU TAKTIKAS',
        'SAVU INTEREŠU AIZSTĀVĒŠANA',
        'MANIPULĀCIJU ATPAZĪŠANA',
        'PĀRLIECINĀŠANA UN ARGUMENTĒŠANA'] },
    { name: 'UPSALES',
      image: 'games/upsales.jpg',
      about: ['PĀRDOŠANAS PAMATALGORITMS',
        'PAPILDPĀRDOŠANA',
        'VAJADZĪBU IZZINĀŠANA',
        'IEBILDUMU ATSPĒKOŠANA'] },
    { name: 'NOTVER MANI, JA VARI',
      image: 'games/saprotimanijavari.jpg',
      about: ['KLIENTA VAJADZĪBU NOSKAIDROŠANAS ALGORITMS',
        'MĒRĶTIECĪGU JAUTĀJUMU UZDOŠANA',
        'KLIENTA KRITĒRIJU IZMANTOŠANA ARGUMENTĀCIJĀ',
        'PRASME RUNĀT KLIENTU VALODĀ'] },
    { name: 'JĀ/NĒ/VARBŪT',
      image: 'games/saprotimanijavari.jpg',
      about: ['5 ARGUMENTĒŠANAS METODES',
        'PAREIZO ARGUMENTU IZVĒLE',
        'PĀRLIECINOŠA UN UZ REZULTĀTU VĒRSTA KOMUNIKĀCIJA',
        'IEBILDUMU ANALĪZE'] },
    { name: 'UNLIMITED ME',
      image: 'games/saprotimanijavari.jpg',
      about: ['4 KOUČINGA METODES',
        'KOUČINGA IZMANTOŠANA VADĪŠANĀ',
        'MĒRĶA UZSTĀDĪŠANA',
        'MĒRĶA SASNIEGŠANAS PLĀNA IZVIRZĪŠANA'] },
    { name: 'ZELTA RESURSS',
      image: 'games/saprotimanijavari.jpg',
      about: ['SASNIEDZAMAJAM MĒRĶIM ATBILSTOŠANAS KOMANDAS IZVEIDOŠANA',
        'IZPRATNE PAR PERSONĀLU KĀ VĒRTĪBU UN RESURSU',
        'FINASIĀLĀ IEGULDĪJUMA EFEKTIVITĀTE PERSONĀLVADĪBĀ',
        'KOMANDAS ATTĪSTĪBAS DINAMIKA'] }
  ],
  seminars: [
    { name: 'VADĪTPRASME',
      image: 'seminars/vaditprasme.jpg',
      about: ['VADĪTĀJA UN LĪDERA GALVENĀS ATBILDĪBAS UN PIENĀKUMI',
        'DARBINIEKU MOTIVĒŠANAS INSTRUMENTI UN IEMAŅAS',
        'DELEĢĒŠANA UN UZDEVUMU DOŠANA',
        'DARBINIEKU POTENCIĀLA NOVĒRTĒŠANA UN ATTĪSTĪŠANA',
        'EFEKTĪVAS KOMUNIKĀCIJAS UN PĀRLIECINĀŠANAS TEHNIKAS']
    },
    { name: 'PĀRDOTPRASME',
      image: 'seminars/pardotprasme.jpg',
      about: ['KLIENTA VAJADZĪBU IZZINĀŠANAS INSTRUMENTI',
        'REZULTATĪVU ATTIECĪBU VEIDOŠANAS PAMATPRINCIPI',
        'PAŠMOTIVĀCIJA UN MĒRĶU SASNIEGŠANA',
        'PRETESTĪBAS UN IEBILDUMU PĀRVARĒŠANA',
        'DARĪJUMU NOSLĒGŠANA UN ILGTERMIŅA ATTIECĪBU UZTURĒŠANA']
    },
    { name: 'LIETIŠĶĀS PĀRRUNAS',
      image: 'seminars/parrunu_vad_noslepumi.jpg',
      about: ['VARAS UN ATTIECĪBU LĪDZSVARS',
        'PĀRRUNU MĒRĶI UN TAKTIKAS',
        'NEVERBĀLĀS KOMUNIKĀCIJAS ATPAZĪŠANA UN IZMANTOŠANA',
        'IETEKMĒJOŠAS KOMUNIKĀCIJAS PAŅĒMIENI']
    },
    { name: 'PRIORITĀTES UN LAIKA PLĀNOŠANA',
      image: 'seminars/prioritates.jpg',
      about: ['ĪSTERMIŅA UN ILGTERMIŅA MĒRĶI',
        'PRIORITĀŠU NOTEIKŠANA',
        'REZULTATĪVAS PLĀNOŠANAS PAMATI',
        'PRDUKTĪVA VAI NELIETDERĪGA LAIKA IZMANTOŠANA']
    },
    { name: 'KONFLIKTU RISINĀŠANA',
      image: 'seminars/konfliktu_ris.jpg',
      about: ['KONFLIKTU RISINĀŠANAS FĀZES',
        'KONFLIKTU RISINĀŠANAS STRATĒĢIJAS',
        'EMOCIJU VADĪŠANA KONFLIKTĀ',
        'KONFLIKTĀ IESAISTĪTOPUŠU MĒRĶI UN NOLŪKI']
    },
    { name: 'INOVATĪVĀ DOMĀŠANA BIZNESĀ',
      image: 'seminars/inovativa_domasana.jpg',
      about: ['INOVATĪVAS DOMĀŠANAS METODES',
        'IDEJU RADĪŠANU VEICINOŠIE UZSKATI',
        'INOVĀCIJĀM DRAUDZĪGAS KULTŪRAS UZTURĒŠANA',
        'IDEJAS PĀRVĒRŠANA DARBĪBU PLĀNĀ']
    },
    { name: 'PĀRLIECINOŠAS UZSTĀŠANĀS PRASMES',
      image: 'seminars/prezentesanas_prasmes.jpg',
      about: ['UZSTĀŠANĀS MĒRĶI',
        'AUDITORIJAS VADĪŠANAS PAŅĒMIENI',
        'EFEKTĪVA INFORMĀCIJAS NODOŠANA',
        'VERBĀLĀ UN NEVERBĀLĀ KOMUNIKĀCIJA']
    },
    { name: 'FINANSES VADĪTĀJIEM',
      image: 'seminars/finanses_vaditajiem.jpg',
      about: ['VADĪBAS GRĀMATVEDĪBAS STRATĒĢIJAS',
        'FINANŠU PLĀNOŠANA UN ANALĪZE',
        'BUDŽETS, NAUDAS PLŪSMA, PEĻŅAS UN ZAUDĒJUMU APRĒĶINS',
        'FINANŠU RĀDĪTĀJU SAVSTARPĒJĀ KORELĀCIJA']
    },
    { name: 'KOMANDAS SALIEDĒŠANA',
      image: 'seminars/komandas_trenins.jpg',
      about: ['EFEKTĪVAS KOMANDAS KRITĒRIJI UN MODELIS',
        'LOMAS UN NOTEIKUMI KOMANDĀ',
        'VIRZĪBA UZ KOPĪGU MĒRĶI',
        'UZ REZULTĀTU VĒRSTA SAVSTARPĒJĀ KOMUNIKĀCIJA']
    },
    { name: 'KRITISKĀ DOMĀŠANA',
      image: 'seminars/parmainu_domasanas_strategija.jpg',
      about: ['CILVĒKU DOMĀŠANAS TIPI',
        'INFORMĀCIJAS FILTRI',
        'FAKTU IEGŪŠANA PRETSTATĀ INTERPRETĀCIJAI',
        'OBJEKTĪVAS INTERPRETĀCIJAS PARAMETRI']
    },
    { name: 'PĀRMAIŅU DOMĀŠANAS STRATĒĢIJA',
      image: 'seminars/parmainu_domasanas_strategija.jpg',
      about: ['PROBLĒMAS DEFINĒŠANA',
        'PROBLĒMU RISINĀŠANAS IDEJAS',
        'UZ RISINĀJUMU VĒRSTAS DARBA KULTŪRAS RADĪŠANA',
        'PRETOŠANĀS IEMESLI PĀRMAIŅĀM']
    },
    { name: 'TRENERU TRENIŅŠ',
      image: 'seminars/koucings.jpg',
      about: ['TRENIŅA MĒRĶI',
        'APMĀCĪBU FORMAS UN SATURA VEIDOŠANAS PRINCIPI',
        'IESAISTI STIMULĒJOŠA VIDE',
        'DARBS AR SAREŽĢĪTIEM KLAUSĪTĀJIEM',
        'PRAKTISKĀ DARBĪBA UN VINGRINĀJUMI']
    }
  ],
  persons: [
    { name: 'VALDIS PURIŅŠ',
      image: 'people/valdisnop.jpg' },
    { name: 'IEVA SAULĪTE',
      image: 'people/ievanop.jpg' },
    { name: 'ARTŪRS GERGELĒVIČS',
      image: 'people/artursnop.jpg' },
    { name: 'SERGEJS MASLOBOJEVS',
      image: 'people/sergejsnop.jpg' },
    { name: 'ALEKSIS DAUME',
      image: 'people/aleksisnop.jpg' },
    { name: 'KRISTIĀNA GRĀVĪTE',
      image: 'people/kristiananop.jpg' },
    { name: 'EMĪLS BRIGMANIS',
      image: 'people/emilsnop.jpg' },
    { name: 'ADRIANS OSKIRKO',
      image: 'people/adriansnop.jpg' },
    { name: 'UĢIS STRAUSS',
      image: 'people/ugisnop.jpg' }
  ],
  stories: [
    { name: 'kāpjam kalnos',
      image: 'banner2.jpg' },
    { name: 'spēlējam florbolu',
      image: 'stories/florbols.jpeg' },
    { name: 'organizējam nometnes bērniem',
      image: 'stories/upe.jpg' },
    { name: 'spēlējam hokeju',
      image: 'stories/hokejs.jpeg' },
    { name: 'braucam misijās',
      image: 'stories/misijas.jpeg' },
    { name: 'ejam pārgājienos',
      image: 'stories/pargajieni.jpg' },
    { name: 'sienam sieru',
      image: 'stories/siers.jpg' },
    { name: 'braucam ar laivām',
      image: 'stories/laivas.jpg' },
    { name: 'muzicējam',
      image: 'stories/muzika.jpeg' },
    { name: 'organizējam mūzikas festivālus',
      image: 'stories/festivals.jpg' },
    { name: 'spēlejam šahu',
      image: 'stories/sahs.jpg' }
  ],
  partners: [
    { name: 'Starptautiski',
      image: 'logo/nti-int.png',
      link: 'nti-group.com' },
    { name: 'Krievija',
      image: 'logo/nti-su.png',
      link: 'nti.su' },
    { name: 'Ukraina',
      image: 'logo/nti-ua.jpg',
      link: 'nordic.in.ua' }
  ],
  contacts: [
    { name: 'CooolToool',
      image: 'logo/coooltoool.png',
      link: 'coooltoool.net' },
    { name: 'IM Games',
      image: 'logo/imgames.png',
      link: 'im-games.org' },
    { name: 'Viennese',
      image: 'logo/viennese.png',
      link: 'viennese.org' }
  ]
}
