export default {
  games: [
    { name: 'MĒRĶIS',
      image: 'merkis.jpg',
      about: ['SAVU UN CITU POZĪCIJU NOZĪMĪGUMS',
        'MĒRĶU UZSTĀDĪŠANA UN SASNIEGŠANA',
        'TAKTISKĀ VADĪBA',
        'PLĀNOŠANA',
        'SAVSTARPĒJĀ KOMUNIKĀCIJA',
        'SADARBĪBA KOMANDĀ'] },
    { name: 'TIME MENTOR OFFICE',
      image: 'timementoroffice.jpg',
      about: ['PRIORITĀŠU NOTEIKŠANA', 'LAIKA PLĀNOŠANA', 'DELEĢĒŠANA', '"NĒ" PATEIKŠANA', 'NESVARĪGO PROCESU ATMEŠANA'] },
    { name: 'SITUĀCIJAS PIRĀTS',
      image: 'situacijaspirats.jpg',
      about: [ 'VADĪBAS STILA ATPAZĪŠANA',
        'VADĪBAS STILA IZVĒLE',
        'VADĪBAS STILA PIELĀGOŠANA',
        'DARBINIEKU IZPRAŠANA' ] },
    { name: 'HOW COULD IT BE?',
      image: 'howcoulditbe.jpg',
      about: ['SADARBĪBA',
        'NOLŪKS UN REZULTĀTS',
        'KOMUNIKĀCIJA',
        'APZINĀTAIS / NEAPZINĀTAIS NOLŪKS'] },
    { name: 'SALAS UN TILTI',
      image: 'salasuntilti.jpg',
      about: ['KOMUNIKĀCIJA',
        'iEKŠĒJĀ SADARBĪBA',
        'ATGRIEZENISKĀ SAITE'] },
    { name: 'KOMNADAS HOKEJS',
      image: 'komandashokejs.jpg',
      about: ['KOMUNIKĀCIJA',
        'MĒRĶU UZSTĀDĪŠANA',
        'PROBLĒMU RISINĀŠANA'] },
    { name: 'LIDOSTA',
      image: 'lidosta.jpg',
      about: ['STRATĒĢISKĀ DOMĀŠANA',
        'ĀTRA LĒMUMU PIEŅEMŠANA GRUPĀ',
        'PAAUGSTINĀTA DARBA EFEKTIVITĀTE'] },
    { name: 'DZĪVĀS VĒRTĪBAS',
      image: 'dzivasvertibas.jpg',
      about: ['VĒRTĪBU IEDZĪVINĀŠANA',
        'SASKAŅOŠANA',
        'PIELIETOŠANA IKDIENĀ',
        'PERSONISKĀS UN UZŅĒMUMA VĒRTĪBAS'] },
    { name: 'FRONTLINE',
      image: 'frontline.jpg',
      about: ['LABAS KLIENTU APKALPOŠANAS PRINCIPI',
        'PIEPĀRDOŠANAS STRATĒĢIJAS',
        'IEMAŅU TRENIŅŠ',
        'PAAUGSTINĀTA MOTIVĀCIJA'] },
    { name: 'PĀRRUNU PAVĒLNIEKS',
      image: 'parrunupavelnieks.jpg',
      about: ['PĀRRUNU TAKTIKAS',
        'KAULĒŠANĀS METODES',
        'REZULTĀTA SASNIEGŠANA',
        'ATPAZĪT UN IZVAIRĪTIES NO MANIPULĀCIJĀM'] },
    { name: 'UPSALES',
      image: 'upsales.jpg',
      about: ['PIEPĀRDOŠANAS ALGORITMS',
        'ARGUMENTĀCIJA',
        'IEBILDUMU ATSPĒKOŠANA',
        'JAUTĀJUMU UZDOŠANA'] },
    { name: 'NOTVER MANI, JA VARI',
      image: 'saprotimanijavari.jpg',
      about: ['VAJADZĪBU NOSKAIDROŠANAS ALGORITMS',
        'KOMUNIKĀCIJAS PRASMES',
        'KVALITATĪVI JAUTĀJUMI'] }
  ],
  seminars: [
    { name: 'VADĪTPRASME',
      image: 'vaditprasme.jpg',
      about: ['SAVU UN CITU POZĪCIJU NOZĪMĪGUMS',
        'MĒRĶU UZSTĀDĪŠANA UN SASNIEGŠANA',
        'TAKTISKĀ VADĪBA',
        'PLĀNOŠANA',
        'SAVSTARPĒJĀ KOMUNIKĀCIJA',
        'SADARBĪBA KOMANDĀ']
    },
    { name: 'PĀRDOTPRASME',
      image: 'pardotprasme.jpg',
      about: ['PRIORITĀŠU NOTEIKŠANA',
        'LIAKA PLĀNOŠANA',
        'DELEĢĒŠANA',
        '"NĒ" PATEIKŠANA',
        'NESVARĪGO PROCESU ATMEŠANA']
    },
    { name: 'PĀRRUNU VADĪŠANAS NOSLĒPUMI',
      image: 'parrunu_vad_noslepumi.jpg',
      about: ['VADĪBAS STILA ATPAZĪŠANA',
        'VADĪBAS STILA IZVĒLE',
        'VADĪBAS STILA PIELĀGOŠANA',
        'DARBINIEKU IZPRAŠANA']
    },
    { name: 'PĀRLIECINĀŠANA UN ARGUMENTĒŠANA',
      image: 'parliec_un_argument.jpg',
      about: [ 'SADARBĪBA',
        'NOLŪKS UN REZULTĀTS',
        'KOMUNIKĀCIJA',
        'APZINĀTAIS / NEAPZINĀTAIS NOLŪKS']
    },
    { name: 'PRIORITĀTES UN LAIKA PLĀNOŠANA',
      image: 'prioritates.jpg',
      about: ['KOMUNIKĀCIJA',
        'iEKŠĒJĀ SADARBĪBA',
        'ATGRIEZENISKĀ SAITE']
    },
    { name: 'KONFLIKTU RISINĀŠANA',
      image: 'konfliktu_ris.jpg',
      about: ['KOMUNIKĀCIJA',
        'MĒRĶU UZSTĀDĪŠANA',
        'PROBLĒMU RISINĀŠANA']
    },
    { name: 'INOVATĪVĀ DOMĀŠANA BIZNESĀ',
      image: 'inovativa_domasana.jpg',
      about: ['STRATĒĢISKĀ DOMĀŠANA',
        'ĀTRA LĒMUMU PIEŅEMŠANA GRUPĀ',
        'PAAUGSTINĀTA DARBA EFEKTIVITĀTE']
    },
    { name: 'PREZENTĒŠANAS UN UZSTĀŠANĀS PRASMES',
      image: 'prezentesanas_prasmes.jpg',
      about: ['VĒRTĪBU IEDZĪVINĀŠANA',
        'SASKAŅOŠANA',
        'PIELIETOŠANA IKDIENĀ',
        'PERSONISKĀS UN UZŅĒMUMA VĒRTĪBAS']
    },
    { name: 'FINANSES VADĪTĀJIEM',
      image: 'finanses_vaditajiem.jpg',
      about: ['LABAS KLIENTU APKALPOŠANAS PRINCIPI',
        'PIEPĀRDOŠANAS STRATĒĢIJAS',
        'IEMAŅU TRENIŅŠ',
        'PAAUGSTINĀTA MOTIVĀCIJA']
    },
    { name: 'KOMANDAS TRENIŅŠ',
      image: 'komandas_trenins.jpg',
      about: ['PĀRRUNU TAKTIKAS',
        'KAULĒŠANĀS METODES',
        'REZULTĀTA SASNIEGŠANA',
        'ATPAZĪT UN IZVAIRĪTIES NO MANIPULĀCIJĀM']
    },
    { name: 'PĀRMAIŅU DOMĀŠANAS STRATĒĢIJA',
      image: 'parmainu_domasanas_strategija.jpg',
      about: ['PIEPĀRDOŠANAS ALGORITMS',
        'ARGUMENTĀCIJA',
        'IEBILDUMU ATSPĒKOŠANA',
        'JAUTĀJUMU UZDOŠANA']
    },
    { name: 'KOUČINGS',
      image: 'koucings.jpg',
      about: ['VAJADZĪBU NOSKAIDROŠANAS ALGORITMS',
        'KOMUNIKĀCIJAS PRASMES',
        'KVALITATĪVI JAUTĀJUMI']
    }
  ],
  persons: [
    { name: 'VALDIS PURIŅŠ',
      image: 'valdisnop.jpg',
      about: 'valdis.gif' },
    { name: 'IEVA SAULĪTE',
      image: 'ievanop.jpg',
      about: 'ieva.gif' },
    { name: 'ARTŪRS GERGALĒVIČS',
      image: 'artursnop.jpg',
      about: 'arturs.gif' },
    { name: 'SERGEJS MASLOBOJEVS',
      image: 'sergejsnop.jpg',
      about: 'sergejs.gif' },
    { name: 'ALEKSIS DAUME',
      image: 'aleksisnop.jpg',
      about: 'aleksis.gif' },
    { name: 'KRISTIĀNA GRĀVĪTE',
      image: 'kristiananop.jpg',
      about: 'kristiana.gif' },
    { name: 'EMĪLS BRIGMANIS',
      image: 'emilsnop.jpg',
      about: 'emils.gif' },
    { name: 'ADRIANS OSKIRKO',
      image: 'adriansnop.jpg',
      about: 'adrians.gif' },
    { name: 'UĢIS STRAUSS',
      image: 'ugisnop.jpg',
      about: 'ugis.gif' }
  ],
  stories: [
    { name: 'Mēs kāpjam kalnos',
      image: 'banner2.jpg' },
    { name: 'Mēs spēlējam florbolu',
      image: 'banner2.jpg' },
    { name: 'Mēs organizējam nometnes bērniem',
      image: 'upe.jpg' },
    { name: 'Mēs spēlējam hokeju',
      image: 'lauvas.jpg' }
  ],
  partners: [
    { name: 'CooolToool',
      image: 'coooltoool.jpg' },
    { name: 'NTI Rus',
      image: 'nti.jpg' }
  ]
}
